### ISSUE TITLE
RFE: embed nginx config in image and configure with environment variables

### ISSUE THREAD

**Issue by mhrivnak** [openshift-assisted/assisted-ui#270]
Currently when deploying facet, it depends on an [nginx config file](https://github.com/openshift-metal3/facet/blob/9f6acd6/deploy/ocp-metal-ui-template.yaml#L22-L42) to be mounted into the image so that the API service will get reverse proxied.

I propose that we permanently add a config template to the image and render it at runtime using environment variables. Currently, the only value it needs is the assisted-service URL.

## Benefits
* Someone trying to run the image does not need to understand nginx configuration or even be aware that nginx is in use. Those are implementation details that can be handled within the container.
* The container's interface becomes simpler. Instead of needing to generate a config file (even if there is an [embedded script](https://github.com/openshift-metal3/facet/blob/7752d03/Dockerfile#L3) to help) and mount that as a file or ConfigMap into the container at a specific path, the user can simply set an environment variable at runtime.
* The current approach does not work well when run outside a cluster. A user has to create the config file on their local filesystem and mount it into the container at runtime. This change would remove the need for that.

## Details
A shell script will become the new ENTRYPOINT for the container image. That shell script will
1. render the template and put it into the right place. Possibly use `envsubst` or some other method for rendering
2. `exec nginx` with whatever args it needs

**Comment by jkilzi** [comment]
@mhrivnak IIUC this has already been implemented, do you believe we can close this issue?

**Comment by mhrivnak** [comment]
@jkilzi you're probably right. If you're confident it's fixed, please close it.

**Comment by mhahl** [comment]
Hi, newbie to the code base, I'm looking though the `deploy/deploy_config.sh` and the `Dockerfile` I'm confused as to how `ASSISTED_SERVICE_URL` comes from the environment, looks like it's being set by the `-u` command line.

Is that correct or have I got this all wrong?

**Comment by jkilzi** [comment]
The `ASSISTED_SERVICE_URL` environment variable can be provided by the environment so it can be overridden inside the deployment script. By default, its value is: `http://assisted-service.assisted-installer.svc.cluster.local:8090`
